### ISSUE TITLE
Publish method push wrong behavior

### ISSUE THREAD

**Issue by schiorean** [CagunA/git-custom-hooks#2]
## Problem description

Publish method will push ALL outstanding branches, not only the selected remote. In general is not an issue but if one of the other branches cannot be fast-forwarded then push will fail and publish will be aborted. 

![pb_push](https://cloud.githubusercontent.com/assets/1135224/26548312/300a56c0-447c-11e7-9ca1-c6099e71f384.png)

## Solution

Publish should push ONLY the selected remote branch.

**Comment by CagunA** [comment]
Fixed !
